apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- $annotations := .Values.serviceAccount.annotations }}
  {{- if .Values.irsa.enabled }}
    {{- if $annotations }}
      {{- $annotations = merge $annotations (dict "eks.amazonaws.com/role-arn" .Values.irsa.roleArn) }}
    {{- else }}
      {{- $annotations = dict "eks.amazonaws.com/role-arn" .Values.irsa.roleArn }}
    {{- end }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}