name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Go test
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # was: actions/checkout@v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # was: actions/setup-go@v7.0.0
        with:
          go-version: "stable"
      - run: |
          go clean -modcache
          make test
  build:
    runs-on: ubuntu-latest
    name: Go build
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # was: actions/checkout@v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # was: actions/setup-go@v7.0.0
        with:
          go-version: "stable"
      - run: |
          go clean -modcache
          make build
          file bin/manager
